name: Continuous Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create build version
        id: createbuildversion
        run: echo "::set-output name=buildversion::$(date +'%y.%m%d').${{ github.run_number }}"

      - name: Check build version
        run: echo "Using version ${{steps.createbuildversion.outputs.buildversion}}"

      - name: Install
        run: npm install

      - name: Buid and Deploy
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.name 'Iana'
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
          npm run deploy
        env:
          REACT_APP_VERSION: ${{steps.createbuildversion.outputs.buildversion}}
